name: static check
on: pull_request

jobs:
  imports:
    name: Imports
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: danhunsaker/golang-github-actions@v1.3.0
      with:
        run: imports
        token: ${{ secrets.GITHUB_TOKEN }}
        flags: "-buildvcs=false"


  errcheck:
    name: Errcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: danhunsaker/golang-github-actions@v1.3.0
      with:
        run: errcheck
        token: ${{ secrets.GITHUB_TOKEN }}
        flags: "-buildvcs=false"

  shadow:
    name: Shadow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: danhunsaker/golang-github-actions@v1.3.0
      with:
        run: shadow
        token: ${{ secrets.GITHUB_TOKEN }}
        flags: "-buildvcs=false"

  staticcheck:
    name: StaticCheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: danhunsaker/golang-github-actions@v1.3.0
      with:
        run: staticcheck
        token: ${{ secrets.GITHUB_TOKEN }}
        flags: "-buildvcs=false"


